#Kubernets service definitions.

apiVersion: v1
kind: Service
metadata:
  name: shop-backend-service
  annotations:
    owners: blue-team
spec:
  selector:
    app: shop-backend-app
    environment: production
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP